import { useState } from "react";

const plans = [{ name: "Starter", price: 0, description: "For small teams finding their rhythm.", features: ["3 projects", "Unlimited tasks", "Realtime workspace"] }, { name: "Growth", price: 29, description: "For teams turning momentum into a system.", features: ["Unlimited projects", "Team analytics", "Priority support"] }, { name: "Scale", price: 89, description: "For organizations operating at full clarity.", features: ["Advanced permissions", "Audit history", "Dedicated support"] }];

export default function Billing() {
  const [selectedPlan, setSelectedPlan] = useState("Growth");
  const [cycle, setCycle] = useState<"monthly" | "annual">("monthly");
  const [notice, setNotice] = useState("");
  const current = plans.find((plan) => plan.name === selectedPlan) ?? plans[1];
  const price = cycle === "annual" ? Math.round(current.price * 0.8) : current.price;

  return <main className="settings-page billing-page"><div className="page-intro"><div><span className="eyebrow">WORKSPACE / BILLING</span><h2>A plan for the pace.</h2><p className="muted">Choose the operating model that fits your team today.</p></div><span className="prototype-badge">PROTOTYPE DATA</span></div><section className="billing-summary"><div><span className="eyebrow">CURRENT PLAN</span><h3>{current.name}</h3><p className="muted">{current.description}</p></div><div className="billing-price"><strong>${price}</strong><span>/ seat / month</span></div><div className="billing-status"><span className="status-chip">Active</span><small>Next renewal: October 24, 2026</small></div></section><div className="billing-controls"><div className="segmented-control"><button className={cycle === "monthly" ? "selected" : ""} onClick={() => setCycle("monthly")}>Monthly</button><button className={cycle === "annual" ? "selected" : ""} onClick={() => setCycle("annual")}>Annual <em>Save 20%</em></button></div><span className="prototype-note">Simulated billing controls</span></div><section className="plan-grid">{plans.map((plan) => <button className={selectedPlan === plan.name ? "plan-card selected" : "plan-card"} key={plan.name} onClick={() => { setSelectedPlan(plan.name); setNotice(`${plan.name} plan selected for preview.`); }}><span className="eyebrow">{plan.name.toUpperCase()}</span><strong>${cycle === "annual" ? Math.round(plan.price * 0.8) : plan.price}<small>/mo</small></strong><p>{plan.description}</p><ul>{plan.features.map((feature) => <li key={feature}>{feature}</li>)}</ul><span className="plan-action">{selectedPlan === plan.name ? "Selected" : "Choose plan"} <span>{"->"}</span></span></button>)}</section>{notice && <p className="success-note">{notice} No payment has been processed.</p>}<section className="invoice-panel"><div><span className="eyebrow">BILLING HISTORY</span><h3>Invoices</h3></div><div className="invoice-row"><span className="invoice-icon">$</span><div><strong>September 24, 2026</strong><small>Growth plan / Prototype invoice</small></div><span className="invoice-amount">${price}.00</span><button className="download-button" onClick={() => setNotice("Invoice download staged for preview.")}>Download</button></div></section></main>;
}